bundle-install: &bundle-install
  run:
    name: Bundle install
    command: |
      bundle check --path vendor/bundle || bundle install --path vendor/bundle --quiet

version: 2
jobs:
  build:
    docker:
      - image: 'quay.io/palettecloud/ruby-cron:v2.4.7'
    working_directory: ~/palette
    steps:
      - checkout
      - restore_cache:
          key: bundle-v2-{{ checksum "Gemfile.lock" }}
      - *bundle-install
      - save_cache:
          key: bundle-v2-{{ checksum "Gemfile.lock" }}
          paths: 
            - ./vendor/bundle
  test-rspec:
    docker:
      - image: 'quay.io/palettecloud/ruby-cron:v2.4.7'
    working_directory: ~/palette
    steps:
      - checkout
      - restore_cache:
          key: bundle-v2-{{ checksum "Gemfile.lock" }}
      - run:
          name: Run Rspec
          command: |
            mkdir -p test-results/rspec
            TESTFILES=$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings --timings-type=classname)
            bundle exec rspec --profile 10 \
              --format RspecJunitFormatter \
              --out test-results/rspec/results_${CIRCLE_NODE_INDEX}.xml \
              --format progress \
              -- ${TESTFILES}
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: test-results


workflows:
  version: 2
  base:
    jobs:
      - build
      - test-rspec
